### PR TITLE
Added an autoChooser

### PR DESCRIPTION
**Pull request by stardust4089**
Added an auto chooser based off WPI lib's example and last year's chooser. Includes:
- Preselected auto in the `SendableChooser`, along with options for every auto.
- Ability for the `SendableChooser` to appear in Shuffleboard. Position of it in shuffleboard can be configured later by the driveteam.

There are only 3 autos added so far, but that will be expanded once we have more. It is very easy to add more in the future.

### CODE REVIEW

**Review by mikemag — APPROVED** [review]
I recall an issue with this very area last year. I didn't experience the problem personally, but the aftermath was a loss of trust in SendableChooser. Personally, I suspect it's fine, but it might be good to log the selection. That way we know what the chooser told us, and what we tried to run. You could use `Command.getName()`. 

You've got a default choice, which is perfect.

**Review by SamarthRao91 — APPROVED** [review]
Looks good! I do want to test this thoroughly during practice to avoid any failures during the competition.

**Review by SamarthRao91 — APPROVED** [review]
Looks good!

**Review by SamarthRao91 — APPROVED** [review]
Looks correct to me.

**Pull request merged**
